services:
  redis:
    container_name: "dksh_datahub_redis_db"
    image: "redis:7-alpine"
    labels:
      tag: "database"
    env_file:
      - .env
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./configs/redis/logs:/var/log/redis
      - redis_data:/data
    networks:
      - db_network
    command: >
      redis-server /usr/local/etc/redis/redis.conf --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    container_name: "dksh_datahub_celery_app"
    user: celeryuser
    build:
      context: .
      dockerfile: celery_Dockerfile
    labels:
      tag: "web_app"
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      REMAP_SIGTERM: SIGQUIT
      REDIS_URL: redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0
    networks:
      - web_network
      - db_network
    command: >
      wait-for-it ${REDIS_HOST}:${REDIS_PORT} --  uvicorn main:app --host 0.0.0.0 --port ${APP_PORT} --reload
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    container_name: "dksh_datahub_worker"
    user: celeryuser
    build:
      context: .
      dockerfile: celery_Dockerfile
    labels:
      tag: "celery_worker"
    env_file:
      - .env
    volumes:
      - .aws:/home/celeryuser/.aws
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REMAP_SIGTERM: SIGQUIT
      REDIS_URL: redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0
      CELERY_TRACK_STARTED: 1
      CELERY_CONCURRENCY: ${CELERY_CONCURRENCY}
      CELERY_POOL: ${CELERY_POOL}
      CELERY_MAX_TASKS_PER_CHILD: ${CELERY_MAX_TASKS_PER_CHILD}
      CELERY_MAX_MEMORY_PER_CHILD: ${CELERY_MAX_MEMORY_PER_CHILD}
    networks:
      - celery_worker_network
      - db_network
    command: >
      wait-for-it ${REDIS_HOST}:${REDIS_PORT} -- celery -A celery_worker worker -E --loglevel=info --concurrency=${CELERY_CONCURRENCY} --pool=${CELERY_POOL} --max-tasks-per-child=${CELERY_MAX_TASKS_PER_CHILD} --max-memory-per-child=${CELERY_MAX_MEMORY_PER_CHILD}
    healthcheck:
      test: [ "CMD", "pgrep", "celery" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - web
      - redis
    restart: unless-stopped
    mem_limit: 512m

  flower:
    container_name: "dksh_datahub_monitoring_app"
    user: celeryuser
    build:
      context: .
      dockerfile: celery_Dockerfile
    labels:
      tag: "monitoring_app"
    env_file:
      - .env
    volumes:
      - .aws:/home/celeryuser/.aws
    command: >
      wait-for-it ${REDIS_HOST}:${REDIS_PORT} --  celery -A celery_worker flower --port=${FLOWER_PORT}
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    networks:
      - web_network
      - db_network
    environment:
      CELERY_BROKER_URL: redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/0
      FLOWER_UNAUTHENTICATED_API: 1
    depends_on:
      - web
      - worker
      - redis
    restart: unless-stopped

networks:
  web_network:
    name: web_network
    driver: bridge
  db_network:
    name: db_network
    driver: bridge
  celery_worker_network:
    name: celery_worker_network
    driver: bridge

volumes:
  redis_data:
    driver: local
